---
version: '2'
services:
  builder:
    build:
      context: .
      dockerfile: Dockerfile.builder
    image: builder
    container_name: builder
    volumes:
      - /pubkey
      - /privkey
    expose:
      - 22
    hostname: builder
    command: ["/root/runit.sh"]
  driver:
    build:
      context: .
      dockerfile: Dockerfile.driver
      args:
        - commit
        - url
        - config
    working_dir: '/home/debian'
    command: ["/home/debian/runit.sh"]
    image: driver
    container_name: driver
    depends_on:
      - builder
    volumes:
      - ./shared:/home/debian/shared
    volumes_from:
      - builder
    hostname: driver
    user: debian
