---
version: '2'
services:
  builder:
    build:
      context: .
      dockerfile: Dockerfile.builder
    image: builder
    container_name: builder
    expose:
      - 22 
    hostname: builder
    command: ["/usr/sbin/sshd", "-D"] 
    volumes:
      - ./shared/root_pubkey:/root/.ssh
      - ./shared/ubuntu_pubkey:/home/ubuntu/.ssh
  driver:
    build:
      context: .
      dockerfile: Dockerfile.driver
      args:
        - commit
        - url
    working_dir: '/home/debian'
    command: ["/home/debian/runit.sh"]
    image: driver
    container_name: driver 
    depends_on:
      - builder
    links:
      - builder
    volumes:
      - ./shared:/home/debian/shared
    hostname: driver
    user: debian
